package AdvLesson02.Exceptions;

import java.util.Random;
import java.util.Scanner;

public class MainEx {
    public static void main(String[] args) {
//        a();

//        try {
//            int b = 10 / 0;
//        } catch (ArithmeticException e) {
//            e.printStackTrace();
//        }
//
//
//        System.out.println("End");

/*        int a, b;
        try {
            int[] mass = {1, 2, 3};
            a = 0;
            b = 10 / a;
            mass[20] = 20;
        } catch (ArithmeticException e) {
            e.printStackTrace();
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }*/


    }
//
//    public static void a() {
//        b();
//    }
//
//    public static void b() {
//        c();
//    }
//
//    public static void c() {
//        int b = 10 / 0;
//    }
}
